ConnectionStrings: 
    MicroservicesClientConnectionString: Data Source=.;Initial Catalog=LibraryMSA;Persist Security Info=True;User ID=galaxy;Password=Password123  
JwtSettings: 
    Key: nskljgfdgokwernglsndgjknsñdjgnskjdfgnlkjsdnfskdjgsdjfkg
    Issuer: https://localhost:44323/
    Audience: Microservices.ConfigServer.Client
    MinutesToExpiration: 10